Add thermoelastic example
evalf/nutils-website pull request #2
Opened 2022-10-19 16:10 UTC by Roxana-P

The pull-requests contains an example for thermoelastic material behavior and shows the following:

1. Creation of a periodic 3D NURBS
2. Solution of the instationary heat equation. 
3. Solution of the thermoelastic problem, with initial values derived from the heat equation. 
4. Export to matplotlib and vtk 

While the physical problem is very simple, the code gives examples for the following features

- vtk export
- using a field instead of a function as initial values 
- NURBS basis in 1D and 2D

2022-10-20 13:45 UTC, joostvanzwieten requested changes

2022-10-20 13:45 UTC, joostvanzwieten commented on examples/user/thermoelasticity.yaml
> +  - deformed_cylinder.vtk
The images listed here are used on the website unmodified. Since browsers can't display VTKs, can you please remove the VTK from the list?

2022-10-20 13:45 UTC, joostvanzwieten commented on examples/user/thermoelasticity.yaml
> +  can be found in, for example, ["Elasticity - Therory, Application and
'Therory' should be 'Theory' and 'Application' is plural.

2022-10-20 13:53 UTC, joostvanzwieten commented
Thanks for the PR. We're happy to add this to the website. Could you squash the changes into a single commit?

Regarding the images: you don't have to include them in your repository. We run all examples ourselves and upload the entire log (including figures) to the website. If you want you can drop the last commit of your repository.

2022-11-10 14:37 UTC, Roxana-P commented
Thank you for the feedback. I adapted the requested changes. Nevertheless I am not sure, if I squashed the commits in the way you expected.

2022-11-10 14:59 UTC, joostvanzwieten commented
Well, not entirely, but that doesn't matter. The last two commits you've pushed are unnecessary. Is it OK if I simply merge the first two commits into the main branch? GitHub probably marks this PR as unmerged, but the [result](https://examples.nutils.org/user-thermoelasticity/) counts.

2022-11-10 16:12 UTC, Roxana-P commented
Yes fine for me. And sorry for the inconvenience.

2022-11-10 21:10 UTC, joostvanzwieten approved these changes

2022-11-10 21:11 UTC, merged

2022-11-10 21:16 UTC, joostvanzwieten commented
I've updated the website. Thanks again for the example!